app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$uploadFile(ctd_files = "../../www/h22ctd.dat") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$setInputs(update = "click")
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(num = 10)
app$snapshot()
app$setInputs(pres_range = c(0, 56))
app$setInputs(pres_range = c(0, 49))
app$setInputs(update = "click")
app$snapshot()
app$snapshotDownload("save1")
app$setInputs(binSize = 2)
app$setInputs(update = "click")
app$snapshot()
app$snapshot()
app$setInputs(hr_range = c(0, 0.7))
app$setInputs(hr_range = c(0, 0.5))
app$setInputs(hr_range = c(0, 0.2))
app$setInputs(update = "click")
app$snapshot()
