app <- ShinyDriver$new(path = "../../", loadTimeout = 1e+05, seed = 1234)
app$snapshotInit("mytest")

app$uploadFile(ctd_files = "../../www/IML2018051/rois/vpr0/d286/h22ctd.dat") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$setInputs(basepath = "~/www")
app$setInputs(update = "click")
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(pres_range = c(0, 53))
app$setInputs(update = "click")
app$snapshot()
app$snapshot()
app$setInputs(hr_range = c(0, 23.7))
app$setInputs(hr_range = c(0, 0.5))
app$setInputs(hr_range = c(0, 0.1))
app$setInputs(hr_range = c(0, 0.3))
app$setInputs(hr_range = c(0, 0.1))
app$setInputs(hr_range = c(0, 0.2))
app$setInputs(update = "click")
app$snapshot()
app$snapshot()
app$snapshot()
