app <- ShinyDriver$new("../../")
app$snapshotInit("test_subsetting")

app$uploadFile(ctd_files = "../../www/h22ctd.dat") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$setInputs(update = "click")
app$snapshot()
app$setInputs(pres_range = c(0, 52))
app$setInputs(pres_range = c(0, 48))
app$setInputs(pres_range = c(0, 51))
app$setInputs(update = "click")
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(hr_range = c(0, 0.3))
app$setInputs(hr_range = c(0, 0.2))
app$setInputs(hr_range = c(0, 0.1))
app$setInputs(update = "click")
app$snapshot()
app$snapshot()
app$snapshot()
